exp_name: 'default'

### Data path
train_label_path: "/home/yhk/data/AI_Security_2021/dataset_no_header/train/trainLabels.csv"
test_A_label_path: "/home/yhk/data/AI_Security_2021/dataset_no_header/test_A/test_ALabels.csv"
test_B_label_path:  "/home/yhk/data/AI_Security_2021/dataset_no_header/test_B/test_BLabels.csv"

train_data_path: "/home/yhk/data/AI_Security_2021/dataset_no_header/train/"
test_A_data_path: "/home/yhk/data/AI_Security_2021/dataset_no_header/test_A/"
test_B_data_path: "/home/yhk/data/AI_Security_2021/dataset_no_header/test_B/"

### output path
log_dir: '/home/yhk/mac_program/ai_competetion/MalConv/log/'
pred_dir: '/home/yhk/mac_program/ai_competetion/MalConv/pred/'
checkpoint_dir: '//home/yhk/mac_program/ai_competetion/MalConv/checkpoint/'

### Parameter
use_gpu: True             #
use_cpu: 16           # Number of cores to use for data loader
display_step: 10           # Std output update rate during training
test_step: 2000             # Test per n step
learning_rate: 0.0001     #
max_step: 20000            # Number of steps to train
batch_size: 20            #
first_n_byte: 200000     # First N bytes of a PE file as the input of MalConv (defualt: 2 million)
window_size: 500          # Kernel size & stride for Malconv (defualt : 500)
sample_cnt: 1             # Number of data sampled for trianing (defualt 1 = all)