exp_name: 'default_famliy_classfication_final_complete_2'

### Data path
train_label_path: "/home/yhk/data/AI_Security_2021/dataset_final/train/train_label.csv"
test_label_path: "/home/yhk/data/AI_Security_2021/dataset_final/test/test_label.csv"

train_data_path: "/home/yhk/data/AI_Security_2021/dataset_final/train/pe"
test_data_path: "/home/yhk/data/AI_Security_2021/dataset_final/test/pe"

### output path
log_dir: '/home/yhk/mac_program/ai_competetion/MalConv/log/'
pred_dir: '/home/yhk/mac_program/ai_competetion/MalConv/pred/'
checkpoint_dir: '/home/yhk/mac_program/ai_competetion/MalConv/checkpoint/'

### Parameter
use_gpu: True             #
use_cpu: 16           # Number of cores to use for data loader
display_step: 10           # Std output update rate during training
test_step: 2000             # Test per n step
learning_rate: 0.0001     #
max_step: 2000000            # Number of steps to train
batch_size: 32            #
first_n_byte: 2000000     # First N bytes of a PE file as the input of MalConv (defualt: 2 million)
window_size: 500          # Kernel size & stride for Malconv (defualt : 500)
sample_cnt: 1            # Number of data sampled for trianing (defualt 1 = all)
cuda_no: 2